language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
